# Generated by Django 4.2 on 2024-09-13 01:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_cliente_telefone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="telefone",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be entered in the format: '+999999999'. Up to 20 digits allowed.",
                        regex="^\\+\\d{9,20}$",
                    )
                ],
            ),
        ),
    ]
